<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.example</groupId>
		<artifactId>tsbank</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>


	<artifactId>infrastructure-restapi</artifactId>
	<name>infrastructure-restapi</name>
	<packaging>jar</packaging>

	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>

	<properties>
		<java.version>21</java.version>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>com.example</groupId>
			<artifactId>usecase</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>com.example</groupId>
			<artifactId>infrastructure-dao-sqlserver</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>com.example</groupId>
			<artifactId>infrastructure-dao-inmemory</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<!-- <profiles>
		<profile>
			<id>sqlserver</id>
			<dependencies>
				<dependency>
					<groupId>com.example</groupId>
					<artifactId>infrastructure-dao-sqlserver</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>inmemory</id>
			<dependencies>
				<dependency>
					<groupId>com.example</groupId>
					<artifactId>infrastructure-dao-inmemory</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
		</profile>
	</profiles> -->
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>3.4.4</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>21</source>
					<target>21</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
